### PR TITLE
Universal Business Language v2.0

### PR DESCRIPTION
**Pull request by tnn**
This is a repackage of the offical OASIS UBL v2.0 specifiction found at
http://docs.oasis-open.org/ubl/os-UBL-2.0/UBL-2.0.html dating 12
December 2006.
The hash sum of the original os-UBL-2.0.zip file is:

MD5  e5f8371423685f23ea02dc4e71e3382c
SHA1 a352fe1c80103c28bc067d980aab6e9aba85a2f5
SHA2 d3eb3356d425bcf16c786d705ebaed99d7da8e581e1a0bcefc4855d734c0ddc9

### CODE REVIEW

**Comment by tnn** [comment]
@fch @sylvest - Could you care to take a look at this to see if proper that these be released as a public maven central (sonatype) artifact? I have included the original LICENSE from the OASIS project.

**Comment by fch** [comment]
The link to the UBL 2.0 schemas on our Integratesite is this:

***************
TSUBL uses the standard UBL 2.0 XSD. You can download it from here:

http://docs.oasis-open.org/ubl/os-UBL-2.0/xsd/

or

http://ubl.xml.org/wiki/ubl-specifications

You find a general introduction to UBL 2.0 here:

http://docs.oasis-open.org/ubl/os-UBL-2.0/UBL-2.0.html

***************

So yes, I can confirm that that is is the correct XSDs

**Comment by JesperTerkelsen** [comment]
@fch But are we allowed to host them here ? This is a public repo.

**Comment by tnn** [comment]
@JesperTerkelsen Reading the 'LICENSE' file from open-oasis.org - the one I have copied into the repository, we should be allowed as long as the license stays with the files. I reached out to Jon Bosak in search of somebody from the open-oasis, but we don't have direct access to members of the technical committee. I would like to post these artifacts in the `org.open-oasis` namespace and Jon suggested that I reached out directory to the TC committee.

**Pull request merged**
